version: '3.8'

services:
  # First Load Balancer to route to API service
  api_load_balancer:
    image: nginx:latest
    container_name: api_load_balancer
    ports:
      - "8081:80"  # Expose port 8081 for API load balancer
    volumes:
      - ./nginx-api.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_service
      - api_service_2

  # API Service 1
  api_service:
    build: ./api-service
    container_name: api_service
    ports:
      - "8080:3000"
    depends_on:
      - minio
      - block_cache_redis
      - metadata_cache_redis

  # API Service 2
  api_service_2:
    build: ./api-service
    container_name: api_service_2
    ports:
      - "8083:3000"
    depends_on:
      - minio
      - block_cache_redis
      - metadata_cache_redis

  # Second Load Balancer to route to S3, Redis, PostgreSQL
  s3_load_balancer:
    image: nginx:latest
    container_name: s3_load_balancer
    ports:
      - "8082:80"  # Expose port 8082 for the second load balancer
    volumes:
      - ./nginx-s3.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
      - block_cache_redis
      - metadata_cache_redis
      - metadata_db

  # Hash Generator Service
  hash_service:
    build: ./hash-service
    container_name: hash_service
    environment:
      POSTGRES_DB: hash_db
      POSTGRES_USER: hash_db_user
      POSTGRES_PASSWORD: hash_db_password
      REDIS_URL: redis://hash_redis:6382
    ports:
      - "5000:3000"
    depends_on:
      - hash_db
      - hash_redis

  hash_db:
    image: postgres:latest
    container_name: hash_db
    environment:
      POSTGRES_DB: hash_db
      POSTGRES_USER: hash_db_user
      POSTGRES_PASSWORD: hash_db_password
    volumes:
      - hash_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Ensure this port is exposed

  hash_redis:
    image: redis:latest
    container_name: hash_redis
    ports:
      - "6382:6379"

  # Simulated S3 Service (MinIO)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO server
      - "9001:9001"  # MinIO console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

  # Redis for block cache
  block_cache_redis:
    image: redis:latest
    container_name: block_cache_redis
    ports:
      - "6380:6379"

  # Redis for metadata cache
  metadata_cache_redis:
    image: redis:latest
    container_name: metadata_cache_redis
    ports:
      - "6381:6379"

  # PostgreSQL for metadata
  metadata_db:
    image: postgres:latest
    container_name: metadata_db
    environment:
      POSTGRES_DB: metadata_db
      POSTGRES_USER: metadata_db_user
      POSTGRES_PASSWORD: metadata_db_password
    volumes:
      - metadata_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Use a different port if 5432 is taken

volumes:
  hash_db_data:
  s3_data:
  metadata_db_data:
